
apiVersion: v1
# Create namespace hyfi
kind: Namespace
metadata:
  name: hyfi
spec: {}
status: {}

---

apiVersion: apps/v1
# for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-hyfi-deployment
  namespace: hyfi
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
# tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-hyfi
        image: dalexander2israel/www_hyfi:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        lifecycle:
          preStop: # Gracefully shutdown nginx
            exec:              
              command:
              - "/usr/sbin/nginx"
              - "-s"
              - "quit"
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
        # securityContext:
        #   privileged: true
        volumeMounts:
        - name: hyfivolume 
          mountPath: /usr/share/nginx/html
          readOnly: false
      volumes:
      - name: hyfivolume 
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: hyfi-service
  namespace: hyfi
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32608
